framework:
    secret: "HiThere"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%.events_default.sqlite"
            broadway:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%.events.sqlite"

broadway:
    read_model:
        repository: elasticsearch
    event_store:
        dbal:
            connection: broadway

parameters:
    storage_suffix: "_%kernel.environment%"
